# Generated by Django 3.2.20 on 2023-08-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_profile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='lastname', max_length=150),
            preserve_default=False,
        ),
    ]
