# Generated by Django 3.2.20 on 2023-08-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='title',
            field=models.CharField(default='Court Reservation', max_length=200),
            preserve_default=False,
        ),
    ]
