# Generated by Django 3.2.20 on 2023-08-09 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='user',
            new_name='created_by',
        ),
    ]
