# Generated by Django 3.2.20 on 2023-08-17 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_auto_20230811_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='time',
        ),
    ]
