# Generated by Django 3.2.20 on 2023-08-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_remove_reservation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='timeslot',
            field=models.IntegerField(choices=[(0, '09:00'), (1, '10:00'), (2, '11:00'), (3, '12:00'), (4, '13:00'), (5, '14:00'), (6, '15:00'), (7, '16:00'), (8, '17:00'), (9, '18:00'), (10, '19:00'), (11, '20:00')], default=0),
            preserve_default=False,
        ),
    ]
